### ISSUE TITLE
Source for example_DZA_intervention file

### ISSUE THREAD

**Issue by pahanc** [mrc-ide/squire#103]
Dear Oliver,
We were wondering if you could please provide more information about the source for the "example_DZA_intervention.csv" file, as we are unsure the source of the "C" value? We looked on the UK government Covid-19 response tracker website, but we couldn't find the "C" value on there. If you could clarify how this would derived it would help us run and interpret the model. Many thanks!
Penelope Hancock and Keyrellous Adib

**Comment by OJWatson** [comment]
Hi there, 

Thanks for the message. The C value is what we have assumed as a first pass the change in R0 is at the given dates. This is based on an early assumption we were using within our global reports on how government interventions impact transmission, which is explained here (https://mrc-ide.github.io/global-lmic-reports/parameters.html). (Also thanks for making me now realise it would be good to link that squire underpins those reports and generally link them together more). The bit relating to interventions is:

> We have incorporated the impact of interventions that have been put in place using data from the Oxford Coronavirus Government Response Tracker. We currently make assumptions about the efficacy of these interventions. We assume that and so the projections should be interpreted as scenarios rather than predictions. Work is ongoing to integrate formal statistical fitting to improve these projections. In summary, school closures are assumed to cause a 10% reduction in contacts. Work closure is assumed to cause 30% reduction in contacts. Banning of public events is assumed to lead to a 5% reduction in contacts while restrictions on movement or a lockdown is not in force. Restrictions of movement is assumed to cause an additional 37.5% reduction in contacts on top of the 40% reduction due to school and work closure, leading to a total 77.5% reduction.

So for Algeria we have the following timings coming from the Oxford database (we do a small amount of data cleaning and filling in missingness - mostly this handles if there is missingness in the last few days for which we assume interventions are the same as they were when they were last reported). 

![image](https://user-images.githubusercontent.com/15249565/82484115-60bc0a80-9ad1-11ea-9911-6a49672cb8f3.png)

Hope that helps. 

P.S. Can't remember if it's said anywhere but the deaths data used is from the ECDC data.

**Comment by pahanc** [comment]
Thank you Oliver, that is super clear! This is a nice way of integrating
the available data. I look forward to seeing the method evolve. We have
been working lately with the CoMo modelling approach (comomodel.net), and
are interested in cross comparison of available approaches for modelling
the spread of coronavirus, particularly in LMICs.
cheers,
Penny

**Comment by OJWatson** [comment]
No worries. Happy to help. 

If you are looking for model comparisons, we have an interface for the squire model at https://covidsim.org/ . This is similar to comomodel.net in that you can pick countries, change parameters (not as many though!) and look at model outputs and download them. Not sure if it helps but it uses the same fitting approach as the reports I linked above so the model is fitted to each countries deaths. 

All the best, 

OJ

**Comment by OJWatson** [comment]
Closing issue. Thanks again Penny
