### ISSUE TITLE
Daily number of infections chart scaling

### ISSUE THREAD

**Issue by pastk** [mrc-ide/squire#105]
Right part of the daily number of infections chart is zoomed into reported cases.
For [Russia](https://mrc-ide.github.io/global-lmic-reports/RUS/) reported cases don't fit into the zoomed chart obviously.

![lmic-scaling-Russia](https://user-images.githubusercontent.com/18434508/82474969-7252e180-9ad4-11ea-848a-1837554a91e3.png)

**Comment by OJWatson** [comment]
Cheers - thanks for this. Will have ago at fixing this for tomorrows update (have already run for today).

**Comment by OJWatson** [comment]
Thanks again. This is now fixed in those reports: https://mrc-ide.github.io/global-lmic-reports/RUS/

![image](https://user-images.githubusercontent.com/15249565/82617929-7f053180-9bc9-11ea-8873-adfae097bc30.png)
