### ISSUE TITLE
Reporting fraction in calibrate raises warnings and freezes grid search

### ISSUE THREAD

**Issue by sidravi1** [mrc-ide/squire#112]
Setting reporting fraction to anything other than 1 causes the particle filter to stall. Upon termination, the following warnings can be seen:

```
1: In dnbinom(data, k, mu = mu, log = TRUE) : non-integer x = 1.250000
2: In dnbinom(data, k, mu = mu, log = TRUE) : non-integer x = 1.250000
3: In dnbinom(data, k, mu = mu, log = TRUE) : non-integer x = 1.250000
4: In dnbinom(data, k, mu = mu, log = TRUE) : non-integer x = 1.250000
5: In dnbinom(data, k, mu = mu, log = TRUE) : non-integer x = 1.250000
6: In dnbinom(data, k, mu = mu, log = TRUE) : non-integer x = 1.250000
...
```

This seems to be because of this line in `calibrate()`:
```
data$deaths <- (data$deaths/reporting_fraction)
```

This line is not needed since we are already correcting the model projects by `phi` in `ll_nbinom`:

```
ll_nbinom <- function(data, model, phi, k, exp_noise) {
  mu <- phi * model + rexp(length(model), rate = exp_noise)
  dnbinom(data, k, mu = mu, log = TRUE)
}
```

Happy to do a PR with this fix if you agree with this.

### To replicate

```
df <- read.csv(squire:::squire_file("extdata/example_DZA.csv"), stringsAsFactors = FALSE)
future::plan(future::multiprocess())

# Fit model
out <- calibrate(
  data = df,
  R0_min = 2,
  R0_max = 4,
  R0_step = 0.5,
  reporting_fraction = 0.7,
  first_start_date = "2020-02-10",
  last_start_date = "2020-02-22",
  day_step = 4,
  replicates = 10,
  n_particles = 20,
  country = "Algeria"
)
```

**Comment by OJWatson** [comment]
Hey Sid, 

Thanks for the raising this and for the clear issue. However, I am a little confused. 

`data$deaths <- (data$deaths/reporting_fraction)` is not in `calibrate` anymore. I removed that when we shifted to calculating it in the likelihood as you pointed out. 

I can't see it in https://github.com/mrc-ide/squire/blob/master/R/calibration.R for example anywhere. What version have you got installed? I'm wondering if you have somehow still got an old version installed somewhere....

Could you post `packageVersion("squire")` for me here?

**Comment by sidravi1** [comment]
Ah! You are totally right. I updated by version of squire and it works well.
Sorry about that.
