### ISSUE TITLE
Plotting deterministic output throws an error

### ISSUE THREAD

**Issue by giovannic** [mrc-ide/squire#126]
Commit: [master](https://github.com/mrc-ide/squire/commit/0ff700ef265ce6b5e6304d3569bc84cfe3cc86a0)

Steps to recreate:
1. Run `plot(squire::run_deterministic_SEIR_model(country='Nigeria'))`

Error message:
`Error in state[, , x] : incorrect number of dimensions`

Traceback:
```
11: is.data.frame(x)
10: rowSums(state[, , x])
9: FUN(X[[i]], ...)
8: vapply(seq_len(replicates), function(x) {
       rowSums(state[, , x])
   }, FUN.VALUE = double(nt))
7: odin_sv(temp_array, replicates = x$parameters$replicates, nt = nt, 
       reduce_age)
6: FUN(X[[i]], ...)
5: lapply(compartments, function(j) {
       temp <- x$output[, unlist(index[j]), ]
       temp_array <- array(temp, dim = c(dim(temp)[1], dim(temp)[2], 
           x$parameters$replicates))
       odin_sv(temp_array, replicates = x$parameters$replicates, 
           nt = nt, reduce_age)
   })
4: format_output(x, var_select = var_select, ...)
3: squire_simulation_plot_prep(x = x, x_var = x_var, var_select = var_select, 
       q = q, summary_f = summary_f, ...)
2: plot.squire_simulation(squire::run_deterministic_SEIR_model(country = "Nigeria"))
1: plot(squire::run_deterministic_SEIR_model(country = "Nigeria"))
```

**Comment by pwinskill** [comment]
I had to put this line `x$output <- x$output[,,1,drop=TRUE]` into the deterministic output formatting function to get it to play nice. Looks like the same issue here

**Comment by pwinskill** [comment]
Actually, having worked a bit more I think adding `dimnames(output$output)[[2]][1] <- "time"` in deterministic output should work?

**Comment by giovannic** [comment]
Fixed by [this PR](https://github.com/mrc-ide/squire/pull/124) Thanks Pete!
