### ISSUE TITLE
deprecated numerical constants in C code

### ISSUE THREAD

**Issue by slwu89** [mrc-ide/squire#177]
Hi @richfitz and @OJWatson,

Not sure if this is an Odin issue or a squire issue, but since I found it while working on safir which depends on squire I'll post here. In the file src/odin.c the constant `DOUBLE_EPS` is used, it seems this has been deprecated on recent versions of R (see https://github.com/wch/r-source/blob/trunk/src/include/R_ext/Constants.h#L46) and `DBL_EPSILON` should now be used (see https://github.com/wch/r-source/commit/bbe621b0cc6bd8acc7c128b3686cbd06bc40e4b4). I noticed src/odin.c said it was generated from odin 1.1.6 which is a bit old so perhaps this is already fixed in odin and squire just needs to be re-generated.

The offending line is here https://github.com/mrc-ide/squire/blob/master/src/odin.c#L6710

**Comment by richfitz** [comment]
odin was updated to fix this in 1.2.4 (CRAN) and 1.3.4 (development) so it should just be a case of regenerating

**Comment by slwu89** [comment]
Cool, thanks.
