### ISSUE TITLE
severity model and age categories

### ISSUE THREAD

**Issue by patrickgtwalker** [mrc-ide/squire#33]
the severity model only seems to have 16 inputs and when you calibrate to deaths with capacity for the whole population it seems to give more deaths than critical cases (summing all IMVs). 

I'm also not sure about the non severe treatement parameters

prob_non_severe_death_treatment	
Probability of death from non severe treated infection. Default = c(0.0125702, 0.0125702, 0.0125702, 0.0125702, 0.0125702, 0.0125702, 0.0125702, 0.013361147, 0.015104687, 0.019164124, 0.027477519, 0.041762108, 0.068531658, 0.105302319, 0.149305732, 0.20349534)

Is this saying that if you have a non-severe disease and you get treatment you still have a 20% chance of dying?? Also is this tagged to original IFR (so if I ramp up capacity to max it should return the original estimates?). Looking really good!!

**Comment by OJWatson** [comment]
addressed in v0.2.0
