### ISSUE TITLE
run_explicit_SEEIR issue when hosp_bed_capacity not specified

### ISSUE THREAD

**Issue by cwhittaker1000** [mrc-ide/squire#39]
Simple running on run_explicit_SEEIR_model e.g. the below:

```
x <- run_explicit_SEEIR_model(country = "Afghanistan")
x$parameters
```
results in:

```
$hosp_bed_capacity
[1] 0

$ICU_bed_capacity
[1] 0
```

which is not what we want. Default parameters not being fed in for some reason.

**Comment by cwhittaker1000** [comment]
Solved by PR #40

**Comment by OJWatson** [comment]
@cwhittaker1000 - could you actually add a bit more to this. So in `run_explicit_SEEIR_model` at this point:

```
  if (is.null(hosp_bed_capacity)) {
    hosp_bed_capacity <- round(5*sum(population)/1000)
  }
  if (is.null(ICU_bed_capacity)) {
    ICU_bed_capacity <- round(3*hosp_bed_capacity/100)
  }
```

Could we first try and source these from the provided country name? I have dumped the bed and gdp.rds you sent me yesterday in data-raw, however there were too few countries...

Either way it would be awesome if you could write a similar function to `get_population` but for these two bed types and then link them here. Also in making that function that would also need a bit more to `data-raw/prepare_raw_data` to make the new data object

**Comment by cwhittaker1000** [comment]
@OJWatson Have sorted this - see PR https://github.com/mrc-ide/squire/pull/47 :) Let me know your thoughts!

**Comment by cwhittaker1000** [comment]
PR #47
