### ISSUE TITLE
matrix 12 is not a matrix

### ISSUE THREAD

**Issue by OJWatson** [mrc-ide/squire#51]
The 12th stored matrix is not a matrix. 

Rewrite the data raw prep to make sure these are all matrices, e.g. test it for algeria @cwhittaker1000

**Comment by cwhittaker1000** [comment]
Temporary fix put in via PR #53 - going to close this issue as the broader issue of the contact matrix generation code not being in the package currently is covered under https://github.com/mrc-ide/squire/issues/1
